name: '20Scoops-CNX-Vault'
description: 'Export secret from vault server'
branding:
  icon: 'toggle-right'
  color: 'red'
inputs:
  VAULT_HOST:
    description:
      'vault server url path example: http://vault-server.com'
    required: true
  VAULT_TOKEN:
    description:
      'vault token for verify and get secrets'
    required: true
  PATH:
    description: 'vault secret path example: aws/secret'
    required: true
  MODULE:
    description: 'vault secret module aws, kv, ssh'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'